### ISSUE TITLE
Game hangs when there are more than 1 player

### ISSUE THREAD

**Issue by rokastve** [domkia/tankz-multiplayer#4]
System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.SortedSet`1.Enumerator.MoveNext()
   at TankzClient.Framework.Scene.Render(Graphics context) in C:\Users\rokas\Desktop\tankz-multiplayer\TankzMultiplayer\TankzClient\Framework\Scene.cs:line 41

**Comment by rokastve** [comment]
Closed by adding lock on entity list
